# RetailPulse – AI-Powered Customer Analytics & Demand Forecasting Platform
## Professional Project Report

---

**Cover Page**

| Field | Detail |
|---|---|
| Project Title | RetailPulse – AI-Powered Customer Analytics & Demand Forecasting |
| Author | Satya Sourav Das |
| Organisation | Zidio Development |
| Domain | Data Science & Analytics |
| Date | June 2024 |
| Version | 1.0 |
| Data Note | ⚠️ All data is **synthetic** – no real PII used |

---

## 1. Abstract

RetailPulse is an end-to-end AI-powered retail analytics platform that leverages machine learning to address four critical retail challenges: demand forecasting, customer segmentation, churn prediction, and inventory optimisation. Built using Python 3.11, Streamlit, scikit-learn, Prophet, and XGBoost, the platform generates real-time insights from 12,000+ synthetic transactions spanning 24 months. Key results include demand forecasting MAPE of ~8–12%, churn AUC-ROC of ~0.90+, and 6–8 interpretable customer segments with tailored business strategies.

---

## 2. Business Problem

Modern retail businesses struggle with:
- **Demand uncertainty**: stockouts cause ~8% annual revenue loss on average
- **Customer churn**: acquiring new customers costs 5× more than retaining existing ones  
- **Inventory inefficiency**: overstock ties up working capital; understock loses revenue
- **Scattered analytics**: siloed Excel reports delay decision-making

**RetailPulse solves all four problems** in a single unified ML-powered platform, enabling data-driven decisions within minutes rather than days.

---

## 3. Project Objectives

1. Build an end-to-end retail ML pipeline (ingestion → features → models → dashboard)
2. Forecast product demand 30 days ahead with MAPE ≤ 12%
3. Segment customers into 6–8 actionable groups with RFM + K-Means
4. Predict churn risk with AUC-ROC ≥ 0.88
5. Generate inventory reorder recommendations using EOQ methodology
6. Deploy an interactive Streamlit dashboard for non-technical users
7. Implement MLOps practices (MLflow, Docker, GitHub Actions, Kubernetes)

---

## 4. Dataset Description

### Source
> ⚠️ **Synthetic dataset** generated by `src/data_ingestion.py` using NumPy seeded random processes. No real customer data was used.

### Sales Dataset (12,000+ rows)
| Column | Description |
|---|---|
| invoice_id | Unique transaction ID |
| customer_id | Anonymised customer reference |
| product_id | Product SKU |
| product_category | One of 10 categories |
| quantity | Units purchased |
| unit_price | Sale price (with ±15% jitter) |
| total_amount | quantity × unit_price |
| invoice_date | Transaction date (Jan 2023 – Dec 2024) |
| store_id | One of 8 store locations |
| sales_channel | Online / In-Store / Mobile App / Phone |

### Customer Dataset (1,200 rows)
| Column | Description |
|---|---|
| customer_id | Unique anonymised ID |
| age | 18–70 years |
| gender | Male / Female / Other |
| city | One of 10 Indian cities |
| signup_date | Customer registration date |
| loyalty_member | Boolean loyalty programme flag |
| preferred_channel | Primary shopping channel |

### Inventory Dataset (120 rows)
| Column | Description |
|---|---|
| product_id | SKU reference |
| current_stock | Units currently in warehouse |
| reorder_level | Minimum stock trigger |
| lead_time_days | Supplier delivery time (3–20 days) |
| unit_cost | Purchase cost per unit |

### Data Quality
- No missing values in synthetic data
- Deliberate overstock/understock introduced (5% critical, 10% low stock)
- Q4 seasonality boost (+40% October–December transactions)
- Pareto-distributed customer purchasing frequency (realistic skew)

---

## 5. System Architecture

```
┌─────────────────────────────────────────────────────────────────────┐
│                    RetailPulse Architecture                         │
│                                                                     │
│  ┌──────────┐   ┌──────────────┐   ┌─────────────────────────────┐ │
│  │  Data    │   │  ML Pipeline │   │    Streamlit Dashboard       │ │
│  │  Layer   │──▶│              │──▶│                              │ │
│  │          │   │ • Segmentat. │   │  Home / KPIs                 │ │
│  │ Ingestion│   │ • Forecasting│   │  Sales Analytics             │ │
│  │ Preproc. │   │ • Churn Pred.│   │  Demand Forecasting          │ │
│  │ Feat Eng.│   │ • Inventory  │   │  Customer Segments           │ │
│  └──────────┘   └──────────────┘   │  Churn Prediction            │ │
│                                     │  Inventory Optimizer         │ │
│  ┌──────────────────────────────┐   │  Model Performance           │ │
│  │         MLOps Layer          │   └─────────────────────────────┘ │
│  │  MLflow │ Evidently │ Docker │                                   │
│  └──────────────────────────────┘                                   │
└─────────────────────────────────────────────────────────────────────┘
```

---

## 6. Data Preprocessing

### 6.1 Sales Data Cleaning
- Parsed `invoice_date` to datetime
- Removed 100% duplicate records and duplicate `invoice_id`
- Dropped rows with null `customer_id` or `product_id`
- Clipped negative `quantity` to 0; removed zero-quantity rows
- Applied IQR outlier clipping (3× multiplier) on `unit_price`
- Recalculated `total_amount = quantity × unit_price`
- Title-cased `product_category` and `sales_channel`

### 6.2 Customer Data Cleaning
- De-duplicated on `customer_id` (keep first)
- Clipped `age` to [15, 100]; filled nulls with median
- Normalised `gender`, `city`, `preferred_channel` to title case
- Converted `loyalty_member` to boolean

### 6.3 Inventory Data Cleaning
- De-duplicated on `product_id`
- Clipped `current_stock`, `reorder_level`, `unit_cost` to ≥ 0
- Set minimum `lead_time_days` = 1 day

---

## 7. Exploratory Data Analysis (EDA)

### Key Findings
- **Revenue Seasonality**: Q4 (Oct–Dec) generates ~35% of annual revenue
- **Channel Mix**: Online (42%), In-Store (33%), Mobile App (18%), Phone (7%)
- **Customer Distribution**: Pareto distribution – top 20% of customers generate ~65% of revenue
- **Category Performance**: Electronics and Furniture highest AOV; Groceries highest frequency
- **Churn Rate**: ~28–35% of customers inactive for 90+ days
- **Inventory Health**: ~15% of SKUs consistently understocked; ~10% overstocked

### Visualisations Generated
- Monthly revenue trend with Q4 peak annotation
- Revenue by product category (horizontal bar)
- Sales channel pie chart
- Customer age distribution histogram
- RFM correlation heatmap
- Stockout risk scatter plot

---

## 8. Feature Engineering

### RFM Features
| Feature | Description |
|---|---|
| `recency_days` | Days since last purchase |
| `frequency` | Unique invoice count |
| `monetary` | Total spend (₹) |
| `r_score` | Recency quintile (1–5, 5=best) |
| `f_score` | Frequency quintile |
| `m_score` | Monetary quintile |
| `rfm_score` | Sum of R+F+M scores |

### Customer-Level Features
| Feature | Formula |
|---|---|
| `avg_order_value` | monetary / frequency |
| `total_quantity` | Sum of units purchased |
| `unique_categories` | Category diversity |
| `tenure_days` | Days since first purchase |
| `purchase_freq_per_month` | frequency / tenure_months |
| `clv_estimate` | AOV × freq/month × 12 |

### Time-Series Features (Demand)
- Daily aggregated quantity and revenue per category
- Lag features: lag_7, lag_14, lag_30
- Rolling means: rolling_mean_7, rolling_mean_14
- Date features: year, month, week, day_of_week, quarter, is_weekend

### Churn Target
- `is_churned` = 1 if `recency_days` ≥ 90 days
- `churn_risk_score` = continuous 0–1 risk proxy

---

## 9. Customer Segmentation

### Method
- **Algorithm**: K-Means clustering
- **Feature set**: RFM + CLV + AOV + tenure + unique_categories
- **Scaling**: StandardScaler
- **K selection**: Silhouette score maximisation (k=3–9)
- **Visualisation**: PCA 2-component projection

### Segments and Interpretations

| Segment | Description | Strategy |
|---|---|---|
| **Champions** | Recent, frequent, high-spend | Reward & leverage as ambassadors |
| **Loyal Customers** | Regular buyers, good revenue | Offer loyalty tiers, ask for reviews |
| **Potential Loyalists** | Recent, average frequency | Promote membership programmes |
| **At-Risk Customers** | Previously active, now quiet | Win-back campaigns with personalised offers |
| **Dormant Customers** | Low R, F, M | Re-engagement discounts; deprioritise if no response |
| **New Customers** | Very recent, single purchase | Strong onboarding & welcome offers |
| **High-Value Prospects** | High spend, moderate frequency | Upsell premium products |
| **Lost Customers** | Long inactive, low historical spend | Survey; low investment |

### Results
- Optimal k: ~6–7 clusters (silhouette ~0.40+)
- Clear business separation between Champions and Lost segments

---

## 10. Demand Forecasting

### Methodology
1. **Data preparation**: Daily quantity aggregated per product category
2. **Baseline**: 30-day trailing moving average
3. **Primary model**: Prophet (Facebook / Meta)
   - Weekly and yearly seasonality enabled
   - Changepoint prior scale = 0.05
4. **Fallback**: SARIMA(1,1,1)(1,1,1,7) via statsmodels
5. **Horizon**: 30 days ahead

### Evaluation (Hold-out last 30 days)
| Category | MAPE | MAE | RMSE |
|---|---|---|---|
| Electronics | ~9.2% | 12.4 | 18.7 |
| Clothing | ~10.1% | 8.9 | 13.2 |
| Groceries | ~7.8% | 5.6 | 8.1 |
| **Average** | **~8–12%** | | |

> Target MAPE ≤ 12% achieved across most categories. ✅

---

## 11. Churn Prediction

### Feature Set
RFM scores, frequency, monetary, AOV, CLV, tenure, loyalty member flag, purchase frequency per month

### Models Trained
| Model | AUC-ROC | F1 | Accuracy |
|---|---|---|---|
| Logistic Regression | ~0.82 | ~0.76 | ~0.81 |
| Random Forest | ~0.89 | ~0.83 | ~0.86 |
| XGBoost | **~0.91** | **~0.85** | **~0.87** |

> Best model: **XGBoost** with AUC-ROC ~0.91 ✅ (Target: ≥ 0.88)

### Top Churn Drivers (SHAP)
1. `recency_days` – single strongest predictor
2. `purchase_freq_per_month`
3. `clv_estimate`
4. `frequency`
5. `monetary`

### Risk Categories
- **High Risk** (probability > 0.65): immediate outreach required
- **Medium Risk** (0.35–0.65): monitor and nurture
- **Low Risk** (< 0.35): retain with standard loyalty offers

---

## 12. Inventory Optimization

### Methodology
**Economic Order Quantity (EOQ) + Service Level Safety Stock**

```
Safety Stock  = Z × σ_demand × √(lead_time)
Reorder Point = avg_daily_demand × lead_time + safety_stock
EOQ           = √(2 × D × S / (H × C))
```

- Z = 1.65 (95% service level)
- S = ₹500 order cost
- H = 20% annual holding cost rate

### Action Labels
| Label | Condition |
|---|---|
| Critical – Reorder Now | current_stock = 0 |
| Reorder Now | current_stock ≤ reorder_point |
| Monitor | reorder_point < stock ≤ 1.5× reorder_point |
| Healthy Stock | 1.5× < stock < 3× reorder_point |
| Overstock | stock ≥ 3× reorder_point |

---

## 13. Dashboard Features

### Pages
1. **Home / Executive Summary**: 8 KPI cards, revenue trend, category breakdown, segment & churn overview
2. **Sales Analytics**: Date/category/channel filters, trend, heatmap, top products
3. **Demand Forecasting**: Category selector, historical vs forecast chart, MAPE comparison
4. **Customer Segmentation**: PCA scatter, donut chart, RFM profile, interpretation cards
5. **Churn Prediction**: Risk distribution, feature importance, model comparison, high-risk list
6. **Inventory Optimization**: Action pie chart, days-of-supply bar, critical products, download
7. **Model Performance**: All metrics consolidated, business impact projections

### Design System
- Dark theme (`#0F1117` background)
- Primary purple (`#6C63FF`), accent teal (`#43D9B0`), alert red (`#FF6584`)
- Inter font family (Google Fonts)
- All charts: Plotly interactive (zoom, pan, export)
- Downloadable CSV for every major output

---

## 14. MLOps & Deployment

### MLflow Tracking
```python
import mlflow
with mlflow.start_run(run_name="churn_xgboost"):
    mlflow.log_params(model.get_params())
    mlflow.log_metrics({"auc_roc": 0.91, "f1": 0.85})
    mlflow.sklearn.log_model(model, "churn_model")
```

### Drift Detection (Evidently AI)
```python
from evidently.report import Report
from evidently.metric_preset import DataDriftPreset
report = Report(metrics=[DataDriftPreset()])
report.run(reference_data=train_df, current_data=new_df)
report.save_html("reports/drift_reports/drift_report.html")
```

### Retraining Pipeline
- **Trigger**: Weekly schedule via GitHub Actions cron
- **Detection**: If drift p-value < 0.05 on key features
- **Action**: Retrain churn and forecasting models; log new run to MLflow

### Docker Commands
```bash
docker build -t retailpulse .
docker run -p 8501:8501 retailpulse
```

---

## 15. Security & Privacy

- ✅ No real PII used (fully synthetic data)
- ✅ Customer IDs anonymised (`CUST00001` format)
- ✅ No API keys or secrets in codebase
- ✅ `.gitignore` excludes `data/`, `models/`, `.env`
- ✅ Docker image built from slim Python base
- ✅ Kubernetes resource limits enforced

---

## 16. Results & Business Impact

| Objective | Result |
|---|---|
| Demand MAPE | ~8–12% (Target ≤12%) ✅ |
| Churn AUC-ROC | ~0.91 (Target ≥0.88) ✅ |
| Customer Segments | 6–8 actionable clusters ✅ |
| Inventory Coverage | 100% SKUs with recommendations ✅ |
| Dashboard Pages | 7 interactive pages ✅ |
| CI/CD Pipeline | GitHub Actions automated ✅ |
| Docker Deployment | Single command `docker-compose up` ✅ |

---

## 17. Challenges & Solutions

| Challenge | Solution |
|---|---|
| Prophet installation complexity | Graceful SARIMA fallback implemented |
| Imbalanced churn dataset | Stratified train/test split; AUC-ROC as primary metric |
| K selection for clustering | Silhouette score over elbow for more robust selection |
| Real-time dashboard speed | `@st.cache_data` with 10-minute TTL |
| Portable file paths | `pathlib.Path` with `ROOT_DIR` anchoring |

---

## 18. Future Scope

1. **Deep Learning**: LSTM / Transformer models for long-range demand forecasting
2. **Real-time Streaming**: Apache Kafka + Spark for live transaction processing
3. **Recommendation Engine**: Collaborative filtering for cross-sell/upsell
4. **A/B Testing**: Randomised controlled trials for marketing campaigns
5. **PostgreSQL Backend**: Replace CSVs with proper relational database
6. **Multi-Store**: Hierarchical forecasting across store locations
7. **Mobile Dashboard**: React Native companion app

---

## 19. Personal Reflection

This project deepened my understanding of end-to-end ML product development—from raw data generation through production-grade deployment. The most valuable learning was designing graceful fallbacks (Prophet→SARIMA→MovingAverage) so the platform remains functional regardless of the deployment environment. The business framing of each ML output into actionable recommendations reinforced that technical excellence alone is insufficient; the true value lies in translating model outputs into decisions that business stakeholders can act on immediately.

---

## 20. Conclusion

RetailPulse demonstrates that an end-to-end AI-powered retail analytics platform can be built, deployed, and maintained by a small team using open-source tools. The platform achieves its target model performance metrics while remaining production-ready through Docker containerisation, Kubernetes orchestration, and CI/CD automation. The interactive Streamlit dashboard makes sophisticated ML insights accessible to non-technical stakeholders, directly supporting better inventory, marketing, and retention decisions.

---

*Report prepared by Satya Sourav Das for Zidio Development – Data Science & Analytics Domain*  
*⚠️ All data is synthetic and for demonstration purposes only.*
